[versions]
adapterDelegates = "4.3.2"
appcompat = "1.7.1"
coilCompose = "2.7.0"
constraintLayout = "2.2.1"
coreKtx = "1.17.0"
coroutines = "1.10.2"
espresso = "3.7.0"
fragmentKtx = "1.8.9"
glide = "5.0.5"
glideCompiler = "5.0.5"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
jodaTime = "2.13.1"
junit = "4.13.2"
junitAndroid = "1.3.0"
kotlinxSerializationJson = "1.9.0"
ktxSerializationConverter = "1.0.0"
ktxSerializationJson = "1.9.0"
material = "1.13.0"
materialVersion = "1.13.0"
navComponents = "2.9.5"
okhttp3Logging = "5.3.0"
retrofit = "3.0.0"
room = "2.8.3"
roomCompiler = "2.8.3"
swipeRefreshLayout = "1.1.0"
timber = "5.0.1"
viewModelKtx = "2.9.4"
agp = "8.12.3"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"

# PLUGINS
androidGradlePlugin = "8.12.3"
kotlin = "2.2.21"
ksp = "2.2.0-2.0.2"
hiltPlugin = "2.57.2"
lifecycleViewmodelSavedstateAndroid = "2.9.4"
protoliteWellKnownTypes = "18.0.1"
roomRuntimeAndroid = "2.8.3"
runtime = "1.9.4"
material3 = "1.4.0"
uiToolingPreview = "1.9.4"
uiTooling = "1.9.4"
adsMobileSdk = "0.19.0-beta01"
foundation = "1.9.4"
coreSplashscreen = "1.0.1"

[libraries]
# ANDROID LIBS
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
#noinspection SimilarGradleDependency
kotlinx-serialization-json-v160 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
viewModelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewModelKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# MATERIAL COMPONENTS
#noinspection SimilarGradleDependency
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
swipeRefreshLayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefreshLayout" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }

# UI
adapterDelegates = { group = "com.hannesdorfmann", name = "adapterdelegates4", version.ref = "adapterDelegates" }

# MEDIA
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glideCompiler = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glideCompiler" }

# TESTS
junit = { group = "junit", name = "junit", version.ref = "junit" }
junitAndroid = { group = "androidx.test.ext", name = "junit", version.ref = "junitAndroid" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

# DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# LOG
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# NETWORK
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okhttp3Logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3Logging" }
ktxSerializationConverter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "ktxSerializationConverter" }

# NAVIGATION
navComponentsFragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navComponents" }
navComponentsUi = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navComponents" }

# MULTITHREADING
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# LOCAL STORAGE (ROOM)
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }

# SYSTEM UTILS
jodaTime = { group = "net.danlew", name = "android.joda", version.ref = "jodaTime" }
ktxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ktxSerializationJson" }
lifecycle-viewmodel-savedstate-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate-android", version.ref = "lifecycleViewmodelSavedstateAndroid" }
protolite-well-known-types = { group = "com.google.firebase", name = "protolite-well-known-types", version.ref = "protoliteWellKnownTypes" }
room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
ads-mobile-sdk = { group = "com.google.android.libraries.ads.mobile.sdk", name = "ads-mobile-sdk", version.ref = "adsMobileSdk" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
